### ISSUE TITLE
Encontre leaks con valgrind

### ISSUE THREAD

**Issue by DanielGuerrero94** [sisoputnfrba/so-nivel-gui-library#10]
Hola queria avisar eso, corri el proceso mapa con valgrind y por mas que liberaba la lista de items y llamaba a nivel_gui_terminar seguia teniendo leaks.
Corri el nivel-gui-test con valgrind y me dice que pierde 124kb, con solo correr nivel_gui_inicializar y despues nivel_gui_terminar ya pierde 72 kb asi que no es culpa de los items solamente.

**Comment by tferraro** [comment]
![image](http://i2.kym-cdn.com/photos/images/facebook/000/349/102/d4b.jpg)

(Ahora posta, danos lo que muestra valgrind para darnos una idea de donde viene el problema y como te impacta)

**Comment by DanielGuerrero94** [comment]
Era mas facil pasarlo, tenes razon.
[valgrindMapa.txt](https://github.com/sisoputnfrba/so-nivel-gui-library/files/560106/valgrindMapa.txt)
Los 124k still reachable parecen ser todos de nivel-gui.
Aca vienen las dudas que me surgieron de correr valgrind quizas da para otro issue que aclare un poco:
No se si realmente me impacta es lo que hablaba hoy con un ayudante, el mapa lo mato con ctrl C y estuve matando al hilo de Deadlock para liberar antes de terminar, de lo cual surge el problema de que me quedo esperando a que finalize y a su vez el hilo esta en un sleep(tiempoDeEsperaDeadlock).
El hilo que tiene la gui lo cierro de la misma forma pero sigue apareciendo en valgrind por lo que digo.

**Comment by RaniAgus** [comment]
¡Encontré el leak! Al `BorrarItem`, este se elimina de la lista pero no se está liberando con `free`, ya que usa `list_remove_by_condition` y no `list_remove_and_destroy_by_condition`.

**Comment by RaniAgus** [comment]
Corregido en #11
