### ISSUE TITLE
Linkeo de curses

### ISSUE THREAD

**Issue by leoxs22** [sisoputnfrba/so-nivel-gui-library#6]
Buenas!

No pude compilar mi proyecto sin agregar además de **-lnivel-gui**, también **-lcurses** 

No se si yo hice cualquiera o se olvidaron de aclararlo, pero con eso ya compila :P

Saludos!

**Comment by gastonprieto** [comment]
Esta perfecto el comentario, justamente eso hacemos en el makefile de la aplicación de prueba.

Lo arreglo en el README.md
