### ISSUE TITLE
#include

### ISSUE THREAD

**Issue by nfederico** [sisoputnfrba/so-nivel-gui-library#7]
Tengo unas dudas sobre esto:

2 - Desde el proyecto que se quiera usar la biblioteca se debe configurar lo siguiente:

-lnivel-gui (en el linker)
# include (en el archivo que se necesite usar la biblioteca) - El include seria? #include<nivel-gui/nivel.h> ? .

**Comment by mgarciaisaia** [comment]
¡Aloha!

En C, con el `#include` lo que hacemos es importar declaraciones que queremos usar sin definir nosotros, ya sea de tipos de datos o de funciones. Si querés usar un tipo de datos que está definido en una biblioteca ([`ITEM_NIVEL`](https://github.com/sisoputnfrba/so-nivel-gui-library/blob/71e7319096c8dbb85169cf59ce9358f394a080ca/nivel-gui/nivel.h#L11-L17), por ejemplo), o una función (como [`nivel_gui_inicializar`](https://github.com/sisoputnfrba/so-nivel-gui-library/blob/71e7319096c8dbb85169cf59ce9358f394a080ca/nivel-gui/nivel.h#L22)), entonces tenés que hacer el `#include` del `.h` que lo declara - en este caso sería algo como `#include <nivel.h>`.

La `nivel-gui` también incluye un `tad_items.h` - si querés usar cosas de ahí, también, vas a tener que `#include`ar el archivo.
