### ISSUE TITLE
Error opening terminal: Unkown

### ISSUE THREAD

**Issue by Matiasarapura** [sisoputnfrba/so-nivel-gui-library#8]
Hola, estaba probando la libreria hice un programa sencillo, linkie nivel-gui y curses. compila bien pero cuando trato de correrlo recibo ese error
<img width="584" alt="screen shot 2016-09-04 at 6 32 33 pm" src="https://cloud.githubusercontent.com/assets/12786877/18234036/fd12368c-72cd-11e6-8754-d3153a60dc5b.png">
Gracias :)

**Comment by mgarciaisaia** [comment]
Je, es cierto.

El nivel necesita una consola interactiva (por lo de ncurses y eso), y la de eclipse no sirve :/

Pegale una corrida por la consola y debería funcionar.

**Comment by gastonprieto** [comment]
Si funciona y queres además queres debuggearla, este video capaz te sirva: https://www.youtube.com/watch?v=MNd8KZlDQUk

**Comment by RaniAgus** [comment]
Se agregó al readme en #11
